name: Build Image and Push, with Notifying

on:
  workflow_call:
    inputs:
      image-name:
        description: 'The full, repository namespaced image name to build (without the tag).'
        required: true
        type: string
      platforms:
        description: "A comma-separated list of platforms to build."
        required: false
        type: string
        default: linux/amd64,linux/arm64/v8
      protected-tags:
        description: 'A list of tags whose container images should be protected from deletion in cleanup. This is in addition to push-branches, which are always protected. CSV format.'
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GH_CONTAINER_REGISTRY_USER:
        required: true
      GH_CONTAINER_REGISTRY_TOKEN:
        required: true

jobs:
  notify-start:
    name: Notify of Start
    if: always()
    uses: unb-libraries/dockworker/.github/workflows/notify-start.yaml@6.x
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-push-images:
    uses: unb-libraries/dockworker/.github/workflows/build-push.yaml@6.x
    needs: [ notify-start ]
    with:
      build-themes: false
      image-name: ${{ inputs.image-name }}
      protected-tags: ${{ inputs.protected-tags }}
      push-branches: '["all"]'
      push-all-branches: true
      platforms: ${{ inputs.platforms }}
    secrets:
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}

  notify-conclusion:
    name: Notify of Conclusion
    uses: unb-libraries/dockworker/.github/workflows/notify-conclusion.yaml@6.x
    needs: [ build-push-images ]
    if: always()
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
